.PHONY: clean All

All:
	@echo "----------Building project:[ C-Philosophenproblem - Debug ]----------"
	@cd "C-Philosophenproblem" && "$(MAKE)" -f  "C-Philosophenproblem.mk"
clean:
	@echo "----------Cleaning project:[ C-Philosophenproblem - Debug ]----------"
	@cd "C-Philosophenproblem" && "$(MAKE)" -f  "C-Philosophenproblem.mk" clean
